name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci
      - name: Build Angular files
        run: npm run build:prod
      - name: Copy Angular files to Spring Boot static directory
        run: |
          cp ./dist/*  ../backend/src/main/resources/static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      # - name: Use Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      - name: Install Railway
        run: npm i -g @railway/cli@2.1.0
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAYTOKEN }}